### ISSUE TITLE
Fix Windows build failures - version 2.8.0

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/perspective-feedstock#148]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

appears multiple windows builds failed with version 2.8.0

The error appears intermittent - and a rerun failed checks might fix the issues - 
 
![image](https://github.com/conda-forge/perspective-feedstock/assets/95496360/01f81301-9877-4324-af7b-4089a86d56d6)

```
ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
copy results:
{}
Failed to upload due to copy from staging to production channel failed. Trying again in 153.93679428100586 seconds
Traceback (most recent call last):
  File "C:\Miniforge\Scripts\upload_package-script.py", line 10, in <module>
    sys.exit(upload_package())
  File "C:\Miniforge\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Miniforge\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Miniforge\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Miniforge\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Miniforge\lib\site-packages\conda_forge_ci_setup\build_utils.py", line 248, in upload_package
    retry_upload_or_check(
  File "C:\Miniforge\lib\site-packages\conda_forge_ci_setup\upload_or_check_non_existence.py", line 317, in retry_upload_or_check
    raise TimeoutError("Did not manage to upload package.  Failing.")
TimeoutError: Did not manage to upload package.  Failing.
##[error]Cmd.exe exited with code '1'.

```

### Installed packages

```shell
Conda build
```

### Environment info

```shell
conda build
```

**Comment by rxm7706** [comment]
Thank you @timkpaine - able to use 2.8.0, windows python 3.10 now. Appreciate it. 
Just to confirm - you want to keep the vs compiler open -- but no plans to upgrade boost yet. 
- https://github.com/conda-forge/perspective-feedstock/issues/149 &
- https://github.com/conda-forge/perspective-feedstock/issues/150

Regards.
